# Generated by Django 4.2.7 on 2025-09-22 00:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=200)),
                ('death_place', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='genealogy/photos/')),
                ('documents', models.JSONField(blank=True, default=list)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_living', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persons',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('subject', 'Sujeto principal'), ('mentioned', 'Mencionado'), ('photographer', 'Fotógrafo'), ('narrator', 'Narrador')], default='subject', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recuerdo de Persona',
                'verbose_name_plural': 'Recuerdos de Personas',
                'db_table': 'person_memories',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('parent', 'Padre/Madre'), ('child', 'Hijo/Hija'), ('sibling', 'Hermano/Hermana'), ('spouse', 'Esposo/Esposa'), ('grandparent', 'Abuelo/Abuela'), ('grandchild', 'Nieto/Nieta'), ('uncle_aunt', 'Tío/Tía'), ('nephew_niece', 'Sobrino/Sobrina'), ('cousin', 'Primo/Prima'), ('other', 'Otro')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='genealogy.person')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='genealogy.person')),
            ],
            options={
                'verbose_name': 'Relación',
                'verbose_name_plural': 'Relaciones',
                'db_table': 'relations',
            },
        ),
    ]
