# Generated by Django 4.2.7 on 2025-09-22 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genealogy', '0001_initial'),
        ('accounts', '0001_initial'),
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmemory',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='memories.memory'),
        ),
        migrations.AddField(
            model_name='personmemory',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_persons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='accounts.vault'),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('person1', 'person2', 'relation_type')},
        ),
        migrations.AlterUniqueTogether(
            name='personmemory',
            unique_together={('person', 'memory')},
        ),
    ]
