# Generated by Django 4.2.7 on 2025-09-22 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('translation', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('greeting', 'Saludo'), ('family', 'Familia'), ('food', 'Comida'), ('love', 'Amor'), ('wisdom', 'Sabiduría'), ('humor', 'Humor'), ('story', 'Historia'), ('advice', 'Consejo'), ('other', 'Otro')], default='other', max_length=20)),
                ('context', models.TextField(blank=True)),
                ('person_mentioned', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(default='es', max_length=10)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='conversation/audio/')),
                ('audio_duration', models.FloatField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_favorite', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_phrases', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='accounts.vault')),
            ],
            options={
                'verbose_name': 'Frase',
                'verbose_name_plural': 'Frases',
                'db_table': 'phrases',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhrasePlayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('duration_played', models.FloatField(blank=True, null=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbacks', to='conversation.phrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_playbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reproducción de Frase',
                'verbose_name_plural': 'Reproducciones de Frases',
                'db_table': 'phrase_playbacks',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('auto_play', models.BooleanField(default=False)),
                ('shuffle_order', models.BooleanField(default=False)),
                ('total_playbacks', models.PositiveIntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_conversation_sessions', to=settings.AUTH_USER_MODEL)),
                ('phrases', models.ManyToManyField(related_name='conversation_sessions', to='conversation.phrase')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sessions', to='accounts.vault')),
            ],
            options={
                'verbose_name': 'Sesión de Conversación',
                'verbose_name_plural': 'Sesiones de Conversación',
                'db_table': 'conversation_sessions',
                'ordering': ['-last_played', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationPlayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('phrases_played', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbacks', to='conversation.conversationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_playbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reproducción de Sesión',
                'verbose_name_plural': 'Reproducciones de Sesiones',
                'db_table': 'conversation_playbacks',
                'ordering': ['-started_at'],
            },
        ),
    ]
